# Generated by Django 3.1.3 on 2020-11-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0002_auto_20201122_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='JournalEntry',
        ),
    ]
