# Generated by Django 3.1.3 on 2020-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0004_auto_20201123_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
