# Generated by Django 3.1.3 on 2020-11-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0005_auto_20201123_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='client_id',
        ),
        migrations.AddField(
            model_name='goal',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
