# Generated by Django 3.1.3 on 2020-11-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capsule', '0007_auto_20201124_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goal', models.TextField()),
                ('priority', models.CharField(default='daily', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('entry', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
