# Generated by Django 3.1.3 on 2020-11-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0008_goal_journalentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
