# Generated by Django 3.1.3 on 2020-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0009_delete_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goal_title', models.TextField()),
                ('goal_description', models.TextField()),
                ('priority', models.CharField(default='daily', max_length=9)),
            ],
        ),
    ]
