# Generated by Django 3.1.3 on 2020-11-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0010_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='goal_title',
            new_name='title',
        ),
    ]
