# Generated by Django 3.1.3 on 2020-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0011_auto_20201125_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
