# Generated by Django 3.1.3 on 2020-11-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0014_journalentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
