# Generated by Django 3.1.3 on 2020-11-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0017_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
