# Generated by Django 3.1.3 on 2020-11-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0022_projectlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlog',
            name='project_id',
        ),
    ]
