# Generated by Django 3.1.3 on 2020-11-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0025_projectlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projectLog',
        ),
    ]
