# Generated by Django 3.1.3 on 2020-11-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0027_projectlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='miniCapsule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
