# Generated by Django 3.1.4 on 2020-12-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0030_auto_20201204_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
