# Generated by Django 3.1.4 on 2020-12-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0031_auto_20201204_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
