# Generated by Django 3.1.4 on 2020-12-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0032_auto_20201204_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
