# Generated by Django 3.1.4 on 2020-12-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0034_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
