# Generated by Django 3.1.4 on 2020-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0036_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('note_type', models.CharField(choices=[('o', 'Opinion'), ('s', 'Summary')], max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
