# Generated by Django 3.1.4 on 2020-12-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0037_booknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
